import { readFile } from 'node:fs/promises'
import pg from 'pg'
import { env } from '../config/env.js'

if (!env.databaseUrlDirect) throw new Error('Thiếu DATABASE_URL_DIRECT hoặc DATABASE_URL')
if (!/^[a-z_][a-z0-9_]*$/i.test(env.databaseSchema)) throw new Error('DATABASE_SCHEMA không hợp lệ')

const sql = await readFile(new URL('./schema.sql', import.meta.url), 'utf8')
const client = new pg.Client({ connectionString: env.databaseUrlDirect, ssl: env.nodeEnv === 'production' ? { rejectUnauthorized: false } : undefined })
await client.connect()
try {
  await client.query(`create schema if not exists ${env.databaseSchema}`)
  await client.query(`set search_path to ${env.databaseSchema},public`)
  await client.query('create table if not exists _tlucs_migrations(id text primary key,applied_at timestamptz not null default now())')
  const done = await client.query(`select 1 from _tlucs_migrations where id='0001_initial'`)
  if (done.rowCount) console.log(`Schema ${env.databaseSchema} đã được áp dụng trước đó.`)
  else {
    await client.query('begin')
    await client.query(sql)
    await client.query(`insert into _tlucs_migrations(id) values('0001_initial')`)
    await client.query('commit')
    console.log(`Đã tạo schema ${env.databaseSchema} cho TLUCS.`)
  }
  await client.query(`create unique index if not exists transactions_request_unique on transactions(request_id) where request_id is not null`)
  await client.query(`create unique index if not exists transactions_sharing_buyer_unique on transactions(sharing_post_id,payer_id) where sharing_post_id is not null`)
  await client.query(`alter table requests add column if not exists course_name text`)
  await client.query(`alter type transaction_status add value if not exists 'cancelled'`)
  await client.query(`alter table users add column if not exists deleted_at timestamptz`)
  await client.query(`alter table users add column if not exists deleted_by uuid references users(id)`)
  await client.query(`alter table posts add column if not exists deleted_at timestamptz`)
  await client.query(`alter table comments add column if not exists deleted_at timestamptz`)
  await client.query(`alter table requests add column if not exists deleted_at timestamptz`)
  await client.query(`alter table sharing_posts add column if not exists deleted_at timestamptz`)
  await client.query(`alter table users drop constraint if exists users_role_check`)
  await client.query(`alter table users add constraint users_role_check check(role in ('member','moderator','admin','super_admin'))`)
  await client.query(`create table if not exists admin_credentials(user_id uuid primary key references users(id) on delete cascade,password_hash text not null,password_changed_at timestamptz not null default now())`)
  await client.query(`create table if not exists admin_audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid not null references users(id),action text not null,target_type text not null,target_id text,reason text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now())`)
  await client.query(`create index if not exists admin_audit_created_idx on admin_audit_logs(created_at desc)`)
  await client.query(`update requests set delivery_mode='online',area_label=null,latitude_blurred=null,longitude_blurred=null where delivery_mode<>'online' or area_label is not null or latitude_blurred is not null or longitude_blurred is not null`)
  await client.query(`update appointments set exact_location=null,meeting_url=null where exact_location is not null or meeting_url is not null`)
  await client.query(`alter table requests drop constraint if exists requests_delivery_mode_check`)
  await client.query(`alter table requests alter column delivery_mode set default 'online'`)
  await client.query(`alter table requests add constraint requests_delivery_mode_check check(delivery_mode='online')`)
  await client.query(`create table if not exists post_gifts(id uuid primary key default gen_random_uuid(),post_id uuid not null references posts(id),sender_id uuid not null references users(id),recipient_id uuid not null references users(id),amount_vnd integer not null check(amount_vnd > 0),fee_vnd integer not null default 0,payout_vnd integer not null,created_at timestamptz not null default now())`)
  await client.query(`create index if not exists post_gifts_post_id_idx on post_gifts(post_id)`)
  await client.query(`alter table post_metrics add column if not exists gift_count integer not null default 0`)
  await client.query(`alter table post_metrics add column if not exists gift_total_vnd integer not null default 0`)
  await client.query(`alter table sharing_access_disputes add column if not exists resolution text`)
  await client.query(`alter table sharing_access_disputes add column if not exists resolved_by uuid references users(id)`)
  await client.query(`alter table comments add column if not exists reaction_count integer not null default 0`)
  await client.query(`alter table comments add column if not exists gift_count integer not null default 0`)
  await client.query(`alter table comments add column if not exists gift_total_vnd integer not null default 0`)
  await client.query(`alter table post_gifts add column if not exists comment_id uuid references comments(id)`)
  await client.query(`alter table post_gifts alter column post_id drop not null`)
  await client.query(`alter table post_gifts drop constraint if exists post_gifts_target_check`)
  await client.query(`alter table post_gifts add constraint post_gifts_target_check check(num_nonnulls(post_id,comment_id)=1)`)
  await client.query(`create index if not exists post_gifts_comment_id_idx on post_gifts(comment_id)`)
  await client.query(`create extension if not exists vector`)
  await client.query(`create table if not exists knowledge_chunks(id text primary key,source text not null,title text not null,content text not null,metadata jsonb not null default '{}',content_hash text not null,embedding vector(768) not null,embedding_model text not null,embedded_at timestamptz not null default now())`)
  await client.query(`create index if not exists knowledge_chunks_source_idx on knowledge_chunks(source)`)
  await client.query(`create index if not exists knowledge_chunks_embedding_hnsw_idx on knowledge_chunks using hnsw (embedding vector_cosine_ops)`)
} catch (error) {
  await client.query('rollback')
  throw error
} finally { await client.end() }
