import { useEffect,useState } from 'react'
import { Navigate,useNavigate } from 'react-router-dom'
import { Activity,AlertTriangle,BookOpen,ClipboardCheck,FileText,LayoutDashboard,LogOut,RefreshCw,Search,ShieldCheck,Users,Wallet } from 'lucide-react'
import LogoIcon from '../components/LogoIcon'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
const money=value=>`${Number(value||0).toLocaleString('vi-VN')}đ`
const tabs=[['dashboard','Tổng quan',LayoutDashboard],['knowledge','Cung–cầu tri thức',BookOpen],['users','Người dùng',Users],['posts','Bài viết',FileText],['requests','Yêu cầu',ClipboardCheck],['sharing','Bảng chia sẻ',BookOpen],['transactions','Giao dịch',Wallet],['cash','Nạp / rút',Wallet],['disputes','Tranh chấp',AlertTriangle],['operations','Kiểm duyệt',ShieldCheck],['audit','Nhật ký',Activity]]
const reasonFor=label=>{const value=prompt(`${label}\nNhập lý do (ít nhất 5 ký tự):`,'');return value?.trim().length>=5?value.trim():null}
export default function AdminPage(){const {session,user,loading,logout}=useAuth(),navigate=useNavigate(),[tab,setTab]=useState('dashboard'),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState('');const token=session?.accessToken
  async function load(){if(!token)return;setBusy(true);setError('');try{let path=tab==='dashboard'?'/admin/dashboard':tab==='knowledge'?'/knowledge/admin/demand':tab==='users'?`/admin/users?q=${encodeURIComponent(q)}`:['posts','requests','sharing'].includes(tab)?`/admin/content/${tab}?q=${encodeURIComponent(q)}`:tab==='transactions'?'/admin/transactions':tab==='cash'?'/admin/cash-requests':tab==='disputes'?'/admin/disputes':tab==='operations'?'/operations/admin/queue':'/admin/audit';setData((await api(path,{token})).data)}catch(e){setError(e.message)}finally{setBusy(false)}}
  // oxlint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{load()},[tab,token]);if(loading)return <div className="grid min-h-screen place-items-center"><RefreshCw className="animate-spin"/></div>;if(!session||!['admin','super_admin'].includes(user?.role))return <Navigate to="/admin/login" replace/>
  async function mutate(path,body,method='POST'){setBusy(true);try{await api(path,{method,token,body});await load()}catch(e){setError(e.message);setBusy(false)}}
  async function changeUser(item,field,value){const reason=reasonFor(`Cập nhật ${item.display_name}`);if(reason)await mutate(`/admin/users/${item.id}`,{[field]:value,reason},'PATCH')}
  function signOut(){logout();navigate('/admin/login',{replace:true})}
  return <div className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[250px_1fr]"><aside className="bg-[#0b1730] p-5 text-white lg:min-h-screen"><div className="rounded-xl bg-white p-3"><LogoIcon/></div><div className="mt-5 rounded-2xl bg-white/10 p-4"><p className="text-xs text-slate-400">Đang đăng nhập</p><b className="mt-1 block truncate">{user.display_name}</b><span className="mt-2 inline-block rounded-full bg-blue-500/20 px-2 py-1 text-xs text-blue-200">{user.role==='super_admin'?'Quản trị tối cao':'Quản trị viên'}</span></div><nav className="mt-6 grid grid-cols-2 gap-2 lg:grid-cols-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>{setTab(id);setData(null);setQ('')}} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${tab===id?'bg-[#2D5BFF]':'text-slate-300 hover:bg-white/10'}`}><Icon size={18}/>{label}</button>)}</nav><button onClick={signOut} className="mt-6 flex items-center gap-2 text-sm font-bold text-red-300"><LogOut size={17}/>Đăng xuất</button></aside><main className="min-w-0 p-5 md:p-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-[#2D5BFF]">TLUCS Control Center</p><h1 className="mt-1 text-3xl font-black">{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><button onClick={load} className="btn-secondary"><RefreshCw size={17} className={busy?'animate-spin':''}/>Làm mới</button></div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 text-red-600">{error}</p>}{['users','posts','requests','sharing'].includes(tab)&&<div className="mt-6 flex rounded-xl border bg-white px-4"><Search className="my-auto text-slate-400"/><input className="w-full border-0 bg-transparent p-3 outline-none" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Tìm kiếm..."/><button onClick={load} className="font-bold text-blue-600">Tìm</button></div>}<section className="mt-6"><Panel tab={tab} data={data} current={user} mutate={mutate} changeUser={changeUser}/></section></main></div>}
function Panel({tab,data,current,mutate,changeUser}){if(tab==='dashboard'){const cards=[['Người dùng',data?.users],['Yêu cầu',data?.requests],['Bài viết',data?.posts],['Bảng chia sẻ',data?.sharing],['Giao dịch',data?.transactions],['Báo cáo mở',data?.open_reports],['Tranh chấp mở',data?.open_disputes],['Chờ xác minh',data?.pending_verifications]];return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><div className="card !transform-none p-5" key={label}><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-3xl">{value??'—'}</b></div>)}</div><div className="card mt-4 !transform-none p-6"><p className="text-sm text-slate-500">Tổng giá trị giao dịch mô phỏng</p><b className="mt-2 block text-3xl text-[#2D5BFF]">{money(data?.gross_vnd)}</b></div></>}
  if(tab==='knowledge')return <div className="grid gap-5"><div><h2 className="mb-3 font-black">Đóng góp chờ duyệt</h2><Table headers={['Tiêu đề','Nguồn','Bằng chứng','Thao tác']}>{data?.pending?.map(x=><tr key={x.id}><td><b>{x.title}</b></td><td>{x.source_type}</td><td>{x.evidence_type}</td><td><div className="flex gap-2"><button onClick={()=>mutate(`/knowledge/admin/${x.id}/review`,{status:'approved'})} className="font-bold text-blue-600">Duyệt</button><button onClick={()=>mutate(`/knowledge/admin/${x.id}/review`,{status:'rejected'})} className="font-bold text-red-600">Từ chối</button></div></td></tr>)}</Table></div><div className="grid gap-5 xl:grid-cols-2"><div><h2 className="mb-3 font-black">Khoảng trống tri thức</h2><Table headers={['Câu hỏi','Số lượt','Lần cuối']}>{data?.gaps?.map(x=><tr key={x.id}><td>{x.example_query}</td><td><b>{x.occurrences}</b></td><td>{new Date(x.last_asked_at).toLocaleDateString('vi-VN')}</td></tr>)}</Table></div><div><h2 className="mb-3 font-black">Người đóng góp</h2><Table headers={['Thành viên','Điểm','Trích dẫn']}>{data?.contributors?.map(x=><tr key={x.id}><td><b>{x.display_name}</b></td><td>{x.knowledge_contribution_points}</td><td>{x.citations}</td></tr>)}</Table></div></div></div>
  if(tab==='users')return <Table headers={['Người dùng','Vai trò','Trạng thái','Số dư','Thao tác']}>{data?.items?.map(x=><tr key={x.id}><td><b>{x.display_name}</b><small>{x.email}</small></td><td>{current.role==='super_admin'&&x.id!==current.id?<select value={x.role} onChange={e=>changeUser(x,'role',e.target.value)}><option>member</option><option>moderator</option><option>admin</option></select>:x.role}</td><td>{x.deleted_at?'Đã xóa':x.status}</td><td>{money(x.available_vnd)}</td><td><div className="flex gap-3">{x.role!=='super_admin'&&<button className="font-bold text-amber-600" onClick={()=>changeUser(x,'status',x.status==='active'?'suspended':'active')}>{x.status==='active'?'Khóa':'Mở khóa'}</button>}<button className="font-bold text-red-600" onClick={()=>{const restore=Boolean(x.deleted_at),reason=reasonFor(`${restore?'Khôi phục':'Xóa mềm'} ${x.display_name}`);if(reason)mutate(`/admin/users/${x.id}/${restore?'restore':'delete'}`,{reason})}}>{x.deleted_at?'Khôi phục':'Xóa mềm'}</button></div></td></tr>)}</Table>
  if(['posts','requests','sharing'].includes(tab))return <Table headers={['Tiêu đề','Tác giả','Trạng thái','Ngày tạo','Thao tác']}>{data?.items?.map(x=><tr key={x.id}><td><b>{x.title||'Không có tiêu đề'}</b></td><td>{x.author_name}</td><td>{x.deleted_at?'Đã xóa':x.status}</td><td>{new Date(x.created_at).toLocaleDateString('vi-VN')}</td><td><button className="font-bold text-red-600" onClick={()=>{const restore=Boolean(x.deleted_at),reason=reasonFor(`${restore?'Khôi phục':'Ẩn'} nội dung`);if(reason)mutate(`/admin/content/${tab}/${x.id}/${restore?'restore':'delete'}`,{reason})}}>{x.deleted_at?'Khôi phục':'Xóa mềm'}</button></td></tr>)}</Table>
  if(tab==='transactions')return <Table headers={['Mã','Người trả','Người nhận','Giá trị','Trạng thái','Thời gian']}>{data?.items?.map(x=><tr key={x.id}><td><small>{x.id.slice(0,8)}</small></td><td>{x.payer_name}</td><td>{x.payee_name||'Chưa ghép'}</td><td><b>{money(x.gross_vnd)}</b></td><td>{x.status}</td><td>{new Date(x.created_at).toLocaleString('vi-VN')}</td></tr>)}</Table>
  if(tab==='cash')return <Table headers={['Mã','Người dùng','Loại / Số tiền','Đối soát tên / STK','Trạng thái','Xử lý']}>{data?.map(x=><tr key={x.id}><td><b>{x.code}</b><small>{new Date(x.created_at).toLocaleString('vi-VN')}</small></td><td><b>{x.display_name}</b><small>{x.email}</small></td><td>{x.kind==='topup'?'Nạp':'Rút'}<small>{money(x.amount_vnd)}</small></td><td>{x.kind==='withdrawal'?<><b>{x.bank_name} · {x.account_number}</b><small>{x.account_name}</small></>:<><b>{x.sender_name||'Chưa khai báo'}</b><small>Tên người chuyển</small></>}</td><td>{x.status}</td><td>{x.status==='pending'?<div className="flex gap-3"><button className="font-bold text-blue-600" onClick={()=>{const bankReference=prompt('Mã giao dịch trên sao kê ngân hàng:'),actualAmountVnd=bankReference&&Number(prompt('Số tiền thực tế đã nhận/chuyển:',x.amount_vnd)),note=actualAmountVnd&&reasonFor('Xác nhận đối soát');if(note)mutate(`/admin/cash-requests/${x.id}/review`,{decision:'approve',bankReference,actualAmountVnd,note})}}>Duyệt</button><button className="font-bold text-red-600" onClick={()=>{const note=reasonFor('Từ chối yêu cầu');if(note)mutate(`/admin/cash-requests/${x.id}/review`,{decision:'reject',note})}}>Từ chối</button></div>:<small>{x.bank_reference||x.review_note||'Đã xử lý'}</small>}</td></tr>)}</Table>
  if(tab==='disputes')return <Table headers={['Người mở','Lý do','Giá trị','Trạng thái','Thao tác']}>{data?.map(x=><tr key={x.id}><td>{x.opened_by_name}</td><td>{x.reason}</td><td>{money(x.gross_vnd)}</td><td>{x.status}</td><td>{x.status==='open'&&<button className="font-bold text-blue-600" onClick={()=>{const resolution=reasonFor('Giải quyết tranh chấp'),decision=resolution&&prompt('Quyết định: refund, release, split hoặc dismiss','dismiss');if(decision)mutate(`/admin/disputes/${x.id}/resolve`,{resolution,decision})}}>Giải quyết</button>}</td></tr>)}</Table>
  if(tab==='operations')return <div className="grid gap-5 xl:grid-cols-3"><Queue title="Xác minh" items={data?.verifications} render={x=><><b>{x.display_name}</b><small>{x.evidence_type}</small><div className="mt-2 flex gap-2"><button onClick={()=>mutate(`/operations/admin/verifications/${x.id}`,{decision:'approved',note:'Đã kiểm tra bằng chứng.'})}>Duyệt</button><button onClick={()=>mutate(`/operations/admin/verifications/${x.id}`,{decision:'rejected',note:'Bằng chứng chưa đạt.'})}>Từ chối</button></div></>}/><Queue title="Báo cáo" items={data?.reports} render={x=><><b>{x.target_type}</b><small>{x.reason}</small><button onClick={()=>mutate(`/operations/admin/reports/${x.id}`,{status:'resolved'})}>Đã xử lý</button></>}/><Queue title="Kiểm duyệt" items={data?.moderation} render={x=><><b>{x.title||x.target_type}</b><small>{x.outcome}</small><div className="mt-2 flex gap-2"><button onClick={()=>mutate(`/operations/admin/moderation/${x.id}`,{decision:'publish',note:'Duyệt thủ công.'})}>Cho đăng</button><button onClick={()=>mutate(`/operations/admin/moderation/${x.id}`,{decision:'reject',note:'Từ chối thủ công.'})}>Từ chối</button></div></>}/></div>
  return <Table headers={['Quản trị viên','Hành động','Đối tượng','Lý do','Thời gian']}>{data?.map(x=><tr key={x.id}><td><b>{x.actor_name}</b><small>{x.actor_email}</small></td><td>{x.action}</td><td>{x.target_type} · {x.target_id?.slice(0,8)}</td><td>{x.reason}</td><td>{new Date(x.created_at).toLocaleString('vi-VN')}</td></tr>)}</Table>}
function Queue({title,items=[],render}){return <div className="card !transform-none p-5"><h2 className="font-black">{title} · {items?.length||0}</h2><div className="mt-3 space-y-3">{items?.map(x=><div className="rounded-xl border p-3" key={x.id}>{render(x)}</div>)}</div></div>}
function Table({headers,children}){return <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{headers.map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y [&_td]:p-4 [&_small]:mt-1 [&_small]:block [&_small]:text-slate-500">{children}</tbody></table></div>}
