/* oxlint-disable react-hooks/exhaustive-deps */
import { useEffect,useRef,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import LogoIcon from '../components/LogoIcon'
import { useAuth } from '../context/AuthContext'
const clientId=import.meta.env.VITE_GOOGLE_CLIENT_ID
export default function LoginPage(){const {loginDemo,loginGoogle,loginPassword,registerPassword}=useAuth();const navigate=useNavigate();const googleButton=useRef(null);const [busy,setBusy]=useState(false);const [googleReady,setGoogleReady]=useState(false);const [error,setError]=useState('');const [mode,setMode]=useState('google');const [passwordMode,setPasswordMode]=useState('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [displayName,setDisplayName]=useState('')
async function finish(login){setBusy(true);setError('');try{const result=await login();navigate(result.user.onboarding_completed?'/':'/register')}catch(e){setError(e.details?.fields?Object.values(e.details.fields)[0]:e.message)}finally{setBusy(false)}}
function promptSavedAccount(){if(!window.google)return setError('Google chưa tải xong. Vui lòng thử lại.');window.google.accounts.id.prompt()}
function submitPassword(e){e.preventDefault();finish(()=>passwordMode==='login'?loginPassword(email,password):registerPassword(email,password,displayName))}
function switchMode(next){setMode(next);setError('')}
function switchPasswordMode(next){setPasswordMode(next);setError('')}
useEffect(()=>{if(!clientId)return;let cancelled=false;function render(){if(cancelled||!window.google||!googleButton.current)return;window.google.accounts.id.initialize({client_id:clientId,callback:response=>finish(()=>loginGoogle(response.credential)),auto_select:true,cancel_on_tap_outside:true,use_fedcm_for_prompt:true});window.google.accounts.id.renderButton(googleButton.current,{theme:'outline',size:'large',shape:'rectangular',text:'continue_with',width:360,locale:'vi'});setGoogleReady(true);window.google.accounts.id.prompt()}if(window.google)render();else{let script=document.querySelector('script[data-tlucs-google]');if(!script){script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.defer=true;script.dataset.tlucsGoogle='true';document.head.appendChild(script)}script.addEventListener('load',render,{once:true})}return()=>{cancelled=true}},[])
return <div className="page flex min-h-[680px] items-center justify-center py-16"><div className="card w-full max-w-md p-8 text-center"><LogoIcon/><h1 className="mt-8 text-3xl font-black">Chào mừng đến TLUCS</h1><p className="mt-3 text-slate-500">Tham gia cộng đồng đại học bằng tài khoản Google hoặc email của bạn.</p>
<div className="mt-6 grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1 text-sm font-bold"><button type="button" onClick={()=>switchMode('google')} className={`rounded-lg py-2 ${mode==='google'?'bg-white shadow text-[#14213d]':'text-slate-500'}`}>Google</button><button type="button" onClick={()=>switchMode('password')} className={`rounded-lg py-2 ${mode==='password'?'bg-white shadow text-[#14213d]':'text-slate-500'}`}>Email &amp; mật khẩu</button></div>
{mode==='google'?<>{clientId?<><div ref={googleButton} className={`mt-8 flex min-h-11 justify-center ${busy?'pointer-events-none opacity-60':''}`}/><button onClick={promptSavedAccount} disabled={busy||!googleReady} className="btn-primary mt-3 w-full justify-center">{busy?'Đang đăng nhập...':'Đăng nhập bằng tài khoản đã lưu'}</button></>:<p className="mt-8 rounded-xl bg-amber-50 p-3 text-sm text-amber-700">Chưa cấu hình Google Client ID.</p>}{import.meta.env.DEV&&<button onClick={()=>finish(loginDemo)} disabled={busy} className="btn-secondary mt-4 w-full justify-center">Dùng tài khoản demo local</button>}</>:
<form className="mt-6 grid gap-3 text-left" onSubmit={submitPassword}>{passwordMode==='register'&&<label>Tên hiển thị<input required minLength="2" maxLength="40" value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Ví dụ: Mèo Máy HCMUS"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@dhqghcm.edu.vn"/></label><label>Mật khẩu<input required type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Ít nhất 8 ký tự"/></label><button disabled={busy} className="btn-primary mt-1 w-full justify-center">{busy?'Đang xử lý...':passwordMode==='login'?'Đăng nhập':'Tạo tài khoản'}</button><p className="text-center text-sm text-slate-500">{passwordMode==='login'?<>Chưa có tài khoản? <button type="button" className="font-bold text-[#2D5BFF]" onClick={()=>switchPasswordMode('register')}>Đăng ký ngay</button></>:<>Đã có tài khoản? <button type="button" className="font-bold text-[#2D5BFF]" onClick={()=>switchPasswordMode('login')}>Đăng nhập</button></>}</p></form>}
{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<p className="mt-6 text-xs leading-5 text-slate-400">Bằng việc tiếp tục, bạn đồng ý với Điều khoản sử dụng và Chính sách quyền riêng tư của TLUCS.</p><p className="mt-6 text-sm text-slate-500">Muốn dùng tài khoản khác? Chọn tài khoản trên nút Google hoặc đăng xuất sau khi vào hệ thống.</p>{mode==='google'&&<p className="mt-3 text-sm text-slate-500">Không dùng Google? <button type="button" className="font-bold text-[#2D5BFF]" onClick={()=>{switchMode('password');switchPasswordMode('register')}}>Đăng ký bằng email</button></p>}</div></div>}
