import { useEffect,useState } from 'react'
import { ArrowLeftRight,Clock3,Gift,MapPin,Search,Sparkles,Wallet } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'
import { useUniversity } from '../context/UniversityContext'
import DetailModal from '../components/DetailModal'

const types={free:{label:'Miễn phí',icon:Gift,color:'bg-emerald-500'},paid:{label:'Trả phí',icon:Wallet,color:'bg-[#2D5BFF]'},exchange:{label:'Trao đổi',icon:ArrowLeftRight,color:'bg-violet-500'}}
const money=value=>Number(value)>0?`${Number(value).toLocaleString('vi-VN')}đ`:'Miễn phí'

export function RequestCard({job,onAccept,onOpen}){
  const type=types[job.kind]||types.free,Icon=type.icon
  return <article onClick={()=>onOpen?.(job)} className={`card flex h-full flex-col p-5 ${onOpen?'cursor-pointer transition hover:-translate-y-1 hover:shadow-lg':''}`}>
    <div className="flex items-start justify-between gap-3"><span className={`flex h-12 w-12 items-center justify-center rounded-xl text-white ${type.color}`}><Icon size={22}/></span><div className="flex flex-wrap justify-end gap-2">{Number.isFinite(job.match_score)&&<span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-[#2D5BFF]">{job.match_score}% phù hợp</span>}<span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">{type.label}</span></div></div>
    <p className="mt-4 text-xs font-extrabold uppercase tracking-wider text-[#2D5BFF]">{job.course_name||'Đời sống đại học'}</p><h3 className="mt-2 text-lg font-bold leading-snug">{job.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{job.description}</p>
    {job.match_reasons?.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{job.match_reasons.map(reason=><span key={reason} className="rounded-lg bg-emerald-50 px-2 py-1 text-[11px] font-bold text-emerald-700">{reason}</span>)}</div>}
    <div className="mt-4 flex flex-wrap gap-3 text-sm text-slate-500"><span className="inline-flex gap-1"><MapPin size={16}/>{job.university_code||job.university_name||'Liên trường'}</span><span className="inline-flex gap-1"><Clock3 size={16}/>{job.duration_minutes} phút</span></div><div className="mt-auto flex items-end justify-between pt-6"><div><p className="text-xs text-slate-400">{job.kind==='paid'?'Ngân sách':'Hình thức'}</p><p className="text-lg font-extrabold text-[#2D5BFF]">{job.kind==='paid'?money(job.amount_vnd):type.label}</p></div><button onClick={event=>{event.stopPropagation();onAccept?.(job)}} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-bold hover:border-[#2D5BFF] hover:text-[#2D5BFF]">Nhận yêu cầu</button></div>
  </article>
}

export default function MarketplacePage(){
  const {session}=useAuth(),{universities,activeUniversityId,setActiveUniversityId}=useUniversity()
  const [q,setQ]=useState(''),[kind,setKind]=useState(''),[timeRange,setTimeRange]=useState(''),[budget,setBudget]=useState(''),[jobs,setJobs]=useState([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[personalized,setPersonalized]=useState(false),[selected,setSelected]=useState(null)
  useEffect(()=>{const params=new URLSearchParams();if(q)params.set('q',q);if(kind)params.set('kind',kind);if(activeUniversityId)params.set('universityId',activeUniversityId);if(timeRange)params.set('timeRange',timeRange);if(budget)params.set('budget',budget);setLoading(true);const timer=setTimeout(()=>api(`/requests?${params}`).then(x=>{setJobs(x.data);setNotice('')}).catch(e=>setNotice(e.message)).finally(()=>setLoading(false)),200);return()=>clearTimeout(timer)},[q,kind,activeUniversityId,timeRange,budget])
  async function personalize(){if(!session)return setNotice('Hãy đăng nhập và hoàn tất hồ sơ để nhận gợi ý phù hợp.');if(personalized){setPersonalized(false);setQ(value=>value+' ');setTimeout(()=>setQ(value=>value.trim()),0);return}setLoading(true);try{const result=await api('/requests/recommended',{token:session.accessToken});setJobs(result.data);setPersonalized(true);setNotice(result.data.length?'Đã xếp hạng theo hồ sơ, chủ đề quan tâm, trường, lịch rảnh và uy tín của bạn.':'Hồ sơ hiện chưa đủ dữ liệu để tìm yêu cầu phù hợp.') }catch(e){setNotice(e.message)}finally{setLoading(false)}}
  async function accept(job){if(!session)return setNotice('Bạn cần đăng nhập trước khi nhận yêu cầu.');try{const result=await api(`/requests/${job.id}/accept`,{method:'POST',token:session.accessToken,body:{}});setNotice(result.mode==='instant'?'Đã ghép! Phòng chat riêng đang được tạo.':'Bạn đã vào hàng đợi ứng viên.');setSelected(null);setJobs(list=>list.filter(x=>x.id!==job.id||result.mode==='queue'))}catch(e){setNotice(e.message)}}
  const selectedType=selected&&(types[selected.kind]||types.free),filtered=[...jobs]
  return <div className="page py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><span className="eyebrow">Hỗ trợ 1–1 · Có động lực · Có cam kết</span><h1 className="mt-4 text-4xl font-extrabold tracking-tight">Bảng yêu cầu</h1><p className="mt-3 text-slate-500">{loading?'Đang tìm...':`${filtered.length} yêu cầu ${personalized?'phù hợp với bạn':'phù hợp với bộ lọc'}.`}</p></div><div className="flex gap-2"><Link to="/yeu-cau-cua-toi" className="btn-secondary">Yêu cầu của tôi</Link><button onClick={personalize} className={personalized?'btn-primary':'btn-secondary'}><Sparkles size={18}/>{personalized?'Bật: Phù hợp với tôi':'Phù hợp với tôi'}</button></div></div>
    <section className="card mt-8 !transform-none p-5"><div className="flex items-center gap-3 rounded-xl border px-4"><Search className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full border-0 py-3 outline-none" placeholder="Tìm môn học, chủ đề hoặc mã trường..."/></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label>Trường<select value={activeUniversityId} onChange={e=>setActiveUniversityId(e.target.value)}><option value="">Tất cả trường</option>{universities.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Hình thức<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">Tất cả hình thức</option><option value="free">Miễn phí</option><option value="paid">Trả phí</option><option value="exchange">Trao đổi</option></select></label><label>Thời gian bắt đầu<select value={timeRange} onChange={e=>setTimeRange(e.target.value)}><option value="">Mọi thời gian</option><option value="24h">Trong 24 giờ</option><option value="3d">Trong 3 ngày</option><option value="7d">Trong 7 ngày</option></select></label><label>Ngân sách<select value={budget} onChange={e=>setBudget(e.target.value)}><option value="">Mọi ngân sách</option><option value="free">Miễn phí</option><option value="under50">1đ–50.000đ</option><option value="50to100">50.001đ–100.000đ</option><option value="over100">Trên 100.000đ</option></select></label></div>{(q||kind||timeRange||budget||activeUniversityId)&&<button onClick={()=>{setQ('');setKind('');setTimeRange('');setBudget('');setActiveUniversityId('')}} className="mt-4 text-sm font-bold text-[#2D5BFF]">Xóa tất cả bộ lọc</button>}</section>
    {notice&&<div className="mt-5 rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-700">{notice}</div>}<div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{loading?<p className="text-slate-400">Đang phân tích hồ sơ và yêu cầu...</p>:filtered.map(j=><RequestCard key={j.id} job={j} onAccept={accept} onOpen={setSelected}/>)}</div>{!loading&&!filtered.length&&<div className="py-20 text-center text-slate-400">Chưa có yêu cầu phù hợp. Hãy bổ sung chủ đề và lịch rảnh trong hồ sơ.</div>}
    <DetailModal open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title} footer={selected&&<button onClick={()=>accept(selected)} className="btn-primary w-full justify-center">Nhận yêu cầu</button>}>{selected&&<><div className="flex flex-wrap gap-2"><span className="tag tag-blue">{selected.course_name||'Đời sống đại học'}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{selectedType.label}</span></div><p className="mt-6 whitespace-pre-line text-base leading-8 text-slate-600">{selected.description}</p><div className="mt-7 grid gap-4 rounded-2xl bg-slate-50 p-5 sm:grid-cols-3"><div><p className="text-xs text-slate-400">Trường</p><b>{selected.university_code||selected.university_name||'Liên trường'}</b></div><div><p className="text-xs text-slate-400">Thời lượng</p><b>{selected.duration_minutes} phút</b></div><div><p className="text-xs text-slate-400">{selected.kind==='paid'?'Ngân sách':'Hình thức'}</p><b className="text-[#2D5BFF]">{selected.kind==='paid'?money(selected.amount_vnd):selectedType.label}</b></div></div></>}</DetailModal></div>
}
