import { useEffect, useState } from 'react'
/* oxlint-disable react-hooks/exhaustive-deps */
import { ArrowDownLeft, ArrowUpRight, Building2, Check, Clock3, Link2, LoaderCircle, Plus, QrCode, ShieldCheck, Wallet, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../lib/api'
import { useAuth } from '../context/AuthContext'

const money = value => `${Number(value || 0).toLocaleString('vi-VN')}đ`
const labels = { demo_topup: 'Nạp số dư mô phỏng', demo_withdraw: 'Rút tiền mô phỏng', manual_topup: 'Nạp qua chuyển khoản', manual_withdrawal: 'Rút về ngân hàng', request_deposit_hold: 'Giữ cọc yêu cầu', request_remaining_hold: 'Giữ tiền còn lại', request_payout: 'Nhận tiền hỗ trợ' }
const denominations = [10000, 20000, 50000, 100000, 200000, 500000]
const banks = ['Vietcombank', 'MB Bank', 'Techcombank', 'BIDV', 'VietinBank', 'ACB']
const paymentAccount = { number: 'DEMO', channels: 'Tài khoản mô phỏng' }

function TopupModal({ onClose, onSuccess, linkedBank, payment }) {
  const [amount, setAmount] = useState(100000), [custom, setCustom] = useState(''), [method, setMethod] = useState('qr'), [senderName,setSenderName]=useState('')
  const [processing, setProcessing] = useState(false), [done, setDone] = useState(false), [error, setError] = useState('')
  const selectedAmount = custom ? Number(custom) : amount
  async function submit() {
    if (!Number.isInteger(selectedAmount) || selectedAmount < 10000 || selectedAmount > 1000000) return setError('Số tiền phải từ 10.000đ đến 1.000.000đ.')
    setError(''); setProcessing(true)
    if(payment?.manualEnabled&&senderName.trim().length<2)return setError('Vui lòng nhập tên người chuyển tiền để admin đối soát.');try { const result=await api(payment?.manualEnabled?'/wallet/topup-requests':'/wallet/demo-topup', { method: 'POST', token: onSuccess.token, body: { amountVnd: selectedAmount,senderName } }); setDone(result.data); await onSuccess() } catch (err) { setError(err.message) } finally { setProcessing(false) }
  }
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && onClose()}>
    <section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl md:p-8">
      <div className="flex items-center justify-between"><div><span className="text-xs font-black uppercase tracking-wider text-[#2D5BFF]">{payment?.manualEnabled?'Chuyển khoản chờ duyệt':'Mô phỏng thanh toán'}</span><h2 className="mt-1 text-2xl font-black">Nạp tiền vào ví</h2></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2" aria-label="Đóng"><X/></button></div>
      {done ? <div className="py-12 text-center"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><Check size={42}/></span><h3 className="mt-6 text-2xl font-black">{payment?.manualEnabled?'Yêu cầu đã được tạo':'Nạp tiền thành công!'}</h3>{payment?.manualEnabled?<div className="mt-4 rounded-2xl bg-blue-50 p-5 text-left text-sm"><p>Chuyển đúng <b>{money(selectedAmount)}</b> đến <b>{done.bank?.name} · {done.bank?.accountNumber}</b></p><p className="mt-2">Chủ tài khoản: <b>{done.bank?.accountName}</b></p><p className="mt-2">Nội dung bắt buộc: <b className="text-[#2D5BFF]">{done.transferContent}</b></p><p className="mt-3 text-amber-700">Tiền chỉ được cộng sau khi admin đối soát.</p></div>:<p className="mt-2 text-slate-500">{money(selectedAmount)} đã được cộng vào ví mô phỏng.</p>}<button onClick={onClose} className="btn-primary mt-7 justify-center">Hoàn tất</button></div> : <>
        <p className="mt-6 text-sm font-bold text-slate-700">Chọn mệnh giá</p><div className="mt-3 grid grid-cols-3 gap-3">{denominations.map(value => <button key={value} onClick={() => { setAmount(value); setCustom('') }} className={`rounded-xl border px-2 py-3 text-sm font-extrabold ${!custom && amount === value ? 'border-[#2D5BFF] bg-blue-50 text-[#2D5BFF]' : 'border-slate-200'}`}>{money(value)}</button>)}</div>
        <label className="mt-5 block">Hoặc nhập số tiền khác<input type="number" min="10000" max="1000000" step="1000" value={custom} onChange={event => setCustom(event.target.value)} placeholder="Từ 10.000đ đến 1.000.000đ"/></label>
        {payment?.manualEnabled&&<label className="mt-5 block">Tên người chuyển tiền<input required minLength="2" value={senderName} onChange={e=>setSenderName(e.target.value)} placeholder="NGUYEN VAN A"/></label>}<p className="mt-6 text-sm font-bold text-slate-700">Hình thức nạp</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><button onClick={() => setMethod('qr')} className={`flex items-center gap-3 rounded-xl border p-4 text-left ${method === 'qr' ? 'border-[#2D5BFF] bg-blue-50' : 'border-slate-200'}`}><QrCode/><span><b className="block">Quét mã QR</b><small className="text-slate-500">Ứng dụng ngân hàng</small></span></button><button disabled={!linkedBank} onClick={() => setMethod('bank')} className={`flex items-center gap-3 rounded-xl border p-4 text-left disabled:opacity-40 ${method === 'bank' ? 'border-[#2D5BFF] bg-blue-50' : 'border-slate-200'}`}><Building2/><span><b className="block">Tài khoản liên kết</b><small className="text-slate-500">{linkedBank ? `${linkedBank.bank} · ${linkedBank.masked}` : 'Chưa liên kết'}</small></span></button></div>
        {method === 'qr' && <div className="mt-5 flex flex-col items-center rounded-2xl bg-slate-50 p-5">{!payment?.manualEnabled&&<img src="/payment-qr.jpg" alt="Mã QR thanh toán mô phỏng" className="max-h-80 w-auto rounded-2xl object-contain shadow-sm"/>}<b className="mt-4 text-lg text-slate-900">{payment?.manualEnabled?'Mã chuyển khoản được tạo ở bước tiếp theo':paymentAccount.channels}</b><p className="mt-1 text-sm text-slate-500">{payment?.manualEnabled?'Chưa chuyển tiền trước khi hệ thống cấp mã.':`Tài khoản: ${paymentAccount.number}`}</p><b className="mt-3 text-xl text-[#2D5BFF]">{money(selectedAmount)}</b></div>}
        {method === 'bank' && linkedBank && <div className="mt-5 rounded-2xl bg-slate-50 p-5"><p className="text-sm text-slate-500">Trích từ tài khoản</p><b className="mt-1 block">{linkedBank.bank} · {linkedBank.masked}</b><p className="mt-4 text-sm text-slate-500">Số tiền</p><b className="mt-1 block text-xl text-[#2D5BFF]">{money(selectedAmount)}</b></div>}
        {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}
        <button disabled={processing} onClick={submit} className="btn-primary mt-6 w-full justify-center">{processing ? <><LoaderCircle className="animate-spin" size={18}/> Đang tạo yêu cầu...</> : <>{payment?.manualEnabled?'Tạo mã nạp':'Nạp'} {money(selectedAmount)}</>}</button><p className="mt-3 text-center text-xs text-amber-600">{payment?.manualEnabled?'Không chuyển tiền nếu tên, số tài khoản hoặc nội dung không khớp.':'Mô phỏng: không phát sinh tiền thật.'}</p>
      </>}
    </section>
  </div>
}

function LinkBankModal({ onClose, onSave, manual }) {
  const [bank, setBank] = useState(banks[0]), [number, setNumber] = useState(''), [name, setName] = useState('')
  async function save(event) { event.preventDefault(); const digits = number.replace(/\D/g, ''); if (digits.length < 6) return; await onSave(manual?{bankCode:bank,bankName:bank,accountNumber:digits,accountName:name}:{ bank, name: name.trim().toUpperCase(), masked: `•••• ${digits.slice(-4)}` }) }
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && onClose()}><form onSubmit={save} className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><span className="text-xs font-black uppercase tracking-wider text-[#2D5BFF]">{manual?'Tài khoản nhận tiền':'Mô phỏng'}</span><h2 className="mt-1 text-2xl font-black">Liên kết ngân hàng</h2></div><button type="button" onClick={onClose}><X/></button></div><label className="mt-6 block">Ngân hàng<select value={bank} onChange={event => setBank(event.target.value)}>{banks.map(value => <option key={value}>{value}</option>)}</select></label><label className="mt-4 block">Số tài khoản<input required inputMode="numeric" value={number} onChange={event => setNumber(event.target.value.replace(/\D/g, ''))} placeholder="Nhập số tài khoản"/></label><label className="mt-4 block">Tên chủ tài khoản<input required minLength="2" value={name} onChange={event => setName(event.target.value)} placeholder="NGUYEN VAN A"/></label><button className="btn-primary mt-6 w-full justify-center"><Link2 size={18}/> Lưu tài khoản</button><p className="mt-3 text-center text-xs text-slate-400">{manual?'Số tài khoản được mã hóa; giao diện chỉ hiện 4 số cuối.':'Thông tin chỉ được lưu mô phỏng trên trình duyệt này.'}</p></form></div>
}

function WithdrawModal({ onClose, onSuccess, linkedBank, balance, payment }) {
  const [amount,setAmount]=useState(100000),[custom,setCustom]=useState(''),[processing,setProcessing]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');const selected=custom?Number(custom):amount
  async function withdraw(){if(!linkedBank)return setError('Vui lòng liên kết tài khoản ngân hàng trước.');if(!Number.isInteger(selected)||selected<10000||selected>10000000)return setError('Số tiền phải từ 10.000đ đến 10.000.000đ.');if(selected>Number(balance))return setError('Số dư khả dụng không đủ.');setError('');setProcessing(true);try{await api(payment?.manualEnabled?'/wallet/withdrawal-requests':'/wallet/demo-withdraw',{method:'POST',token:onSuccess.token,body:{amountVnd:selected}});setDone(true);await onSuccess()}catch(err){setError(err.message)}finally{setProcessing(false)}}
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl bg-white p-7 shadow-2xl"><div className="flex justify-between"><div><span className="text-xs font-black uppercase tracking-wider text-[#2D5BFF]">Mô phỏng thanh toán</span><h2 className="mt-1 text-2xl font-black">Rút tiền về ngân hàng</h2></div><button onClick={onClose}><X/></button></div>{done?<div className="py-12 text-center"><span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><Check size={42}/></span><h3 className="mt-6 text-2xl font-black">Rút tiền thành công!</h3><p className="mt-2 text-slate-500">{money(selected)} đang được chuyển mô phỏng đến {linkedBank?.bank}.</p><button onClick={onClose} className="btn-primary mt-7">Hoàn tất</button></div>:<><div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Tài khoản nhận</p><b>{linkedBank?`${linkedBank.bank} · ${linkedBank.masked}`:'Chưa liên kết ngân hàng'}</b><p className="mt-3 text-xs text-slate-400">Số dư khả dụng: {money(balance)}</p></div><p className="mt-5 text-sm font-bold">Chọn số tiền</p><div className="mt-3 grid grid-cols-3 gap-3">{denominations.map(value=><button key={value} onClick={()=>{setAmount(value);setCustom('')}} className={`rounded-xl border px-2 py-3 text-sm font-extrabold ${!custom&&amount===value?'border-[#2D5BFF] bg-blue-50 text-[#2D5BFF]':'border-slate-200'}`}>{money(value)}</button>)}</div><label className="mt-5 block">Hoặc nhập số tiền khác<input type="number" min="10000" max="1000000" step="1000" value={custom} onChange={event=>setCustom(event.target.value)}/></label>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<button disabled={processing||!linkedBank} onClick={withdraw} className="btn-primary mt-6 w-full justify-center">{processing?<><LoaderCircle className="animate-spin" size={18}/> Đang xử lý...</>:`Rút ${money(selected)}`}</button><p className="mt-3 text-center text-xs text-amber-600">Mô phỏng: không phát sinh chuyển khoản thật.</p></>}</section></div>
}

export default function WalletPage() {
  const { session } = useAuth(); const [wallet, setWallet] = useState(null), [payment,setPayment]=useState(null), [error, setError] = useState(''), [topup, setTopup] = useState(false), [withdrawing,setWithdrawing]=useState(false), [linking, setLinking] = useState(false)
  const [linkedBank, setLinkedBank] = useState(() => { try { return JSON.parse(localStorage.getItem('tlucs-demo-bank')) } catch { return null } })
  const load = () => session && Promise.all([api('/wallet', { token: session.accessToken }),api('/wallet/cash-requests',{token:session.accessToken})]).then(([result,pay])=>{setWallet(result.data);setPayment(pay.data);if(pay.data.account)setLinkedBank({bank:pay.data.account.bankName,masked:pay.data.account.masked,name:pay.data.account.accountName})}).catch(err => setError(err.message))
  useEffect(() => { load() }, [session])
  async function saveBank(bank) {if(payment?.manualEnabled){await api('/wallet/payout-account',{method:'PUT',token:session.accessToken,body:bank});await load()}else localStorage.setItem('tlucs-demo-bank', JSON.stringify(bank));setLinkedBank(payment?.manualEnabled?null:bank);setLinking(false) }
  if (!session) return <div className="page py-24 text-center"><h1 className="text-3xl font-black">Bạn cần đăng nhập để mở ví</h1><Link to="/login" className="btn-primary mt-6">Đăng nhập</Link></div>
  return <div className="page py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><span className="eyebrow"><Wallet size={15}/> Ví mô phỏng</span><h1 className="mt-4 text-4xl font-black">Ví TLUCS</h1><p className="mt-3 text-slate-500">Theo dõi tiền khả dụng, đang giữ và mọi thay đổi trong sổ cái.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={() => linkedBank?setWithdrawing(true):setLinking(true)}><ArrowUpRight size={18}/> Rút tiền</button><button className="btn-primary" onClick={() => setTopup(true)}><Plus size={18}/> Nạp tiền</button></div></div>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-red-600">{error}</p>}
    <div className="mt-8 grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-[#183153] p-6 text-white"><p className="text-sm text-slate-300">Số dư khả dụng</p><b className="mt-3 block text-3xl">{money(wallet?.available_vnd)}</b></div><div className="card p-6"><p className="flex items-center gap-2 text-sm text-slate-500"><Clock3 size={17}/> Đang được giữ</p><b className="mt-3 block text-3xl">{money(wallet?.pending_vnd)}</b></div><div className="card p-6"><p className="flex items-center gap-2 text-sm text-slate-500"><ShieldCheck size={17}/> Phí nền tảng</p><b className="mt-3 block text-3xl">1%</b><p className="mt-2 text-xs text-slate-400">Chỉ tính khi giải ngân thành công</p></div></div>
    <section className="card mt-8 flex flex-wrap items-center justify-between gap-5 p-6"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-50 text-[#2D5BFF]"><Building2/></span><div><h2 className="font-extrabold">Tài khoản ngân hàng</h2><p className="mt-1 text-sm text-slate-500">{linkedBank ? `${linkedBank.bank} · ${linkedBank.masked} · ${linkedBank.name}` : 'Liên kết để nạp tiền nhanh hơn'}</p></div></div><button onClick={() => setLinking(true)} className="btn-secondary"><Link2 size={17}/> {linkedBank ? 'Thay đổi' : 'Liên kết'}</button></section>
    <section className="card mt-8 overflow-hidden"><div className="border-b p-5"><h2 className="text-xl font-extrabold">Lịch sử sổ cái</h2></div>{wallet?.entries?.length ? wallet.entries.map(entry => <div className="flex items-center gap-4 border-b px-5 py-4 last:border-0" key={entry.id}><span className={`flex h-10 w-10 items-center justify-center rounded-full ${entry.direction === 'credit' ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-600'}`}>{entry.direction === 'credit' ? <ArrowDownLeft size={19}/> : <ArrowUpRight size={19}/>}</span><div className="flex-1"><b className="text-sm">{labels[entry.entry_type] || entry.entry_type}</b><p className="text-xs text-slate-400">{new Date(entry.created_at).toLocaleString('vi-VN')}</p></div><b className={entry.direction === 'credit' ? 'text-emerald-600' : 'text-slate-700'}>{entry.direction === 'credit' ? '+' : '-'}{money(entry.amount_vnd)}</b></div>) : <p className="p-10 text-center text-slate-400">Chưa có giao dịch nào.</p>}</section>
    {payment?.requests?.length>0&&<section className="card mt-8 p-5"><h2 className="font-extrabold">Yêu cầu nạp/rút gần đây</h2><div className="mt-3 space-y-2">{payment.requests.map(x=><div key={x.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span><b>{x.code}</b> · {x.kind==='topup'?'Nạp':'Rút'}</span><span>{money(x.amount_vnd)} · {x.status}</span></div>)}</div></section>}
    {topup && <TopupModal payment={payment} linkedBank={linkedBank} onClose={() => setTopup(false)} onSuccess={Object.assign(async () => { await load() }, { token: session.accessToken })}/>} {withdrawing&&<WithdrawModal payment={payment} linkedBank={linkedBank} balance={wallet?.available_vnd} onClose={()=>setWithdrawing(false)} onSuccess={Object.assign(async()=>{await load()},{token:session.accessToken})}/>} {linking && <LinkBankModal manual={payment?.manualEnabled} onClose={() => setLinking(false)} onSave={saveBank}/>} </div>
}
