import crypto from 'node:crypto'
import { database } from '../db/connection.js'
import { env } from '../config/env.js'
import { notify } from './notificationService.js'

const error=(message,status=422,code='INVALID_PAYMENT_REQUEST')=>Object.assign(new Error(message),{status,code})
const amountOf=value=>{const amount=Number(value);if(!Number.isInteger(amount)||amount<10000||amount>10000000)throw error('Số tiền phải từ 10.000đ đến 10.000.000đ.');return amount}
const manualEnabled=()=>env.paymentMode==='manual_review'
const requireManual=()=>{if(!manualEnabled())throw error('Thanh toán chuyển khoản thật chưa được bật.',503,'MANUAL_PAYMENT_DISABLED')}
const key=()=>{const raw=env.paymentDataEncryptionKey;if(!raw||raw.length<32)throw error('Thiếu PAYMENT_DATA_ENCRYPTION_KEY tối thiểu 32 ký tự.',503,'PAYMENT_ENCRYPTION_NOT_CONFIGURED');return crypto.createHash('sha256').update(raw).digest()}
const encrypt=value=>{const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key(),iv);const body=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${body.toString('base64url')}`}
const decrypt=value=>{const [i,t,b]=value.split('.');const decipher=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64url'));decipher.setAuthTag(Buffer.from(t,'base64url'));return decipher.update(Buffer.from(b,'base64url'),undefined,'utf8')+decipher.final('utf8')}
const normalizeAccount=value=>String(value||'').replace(/\s/g,'')
const hashAccount=value=>crypto.createHmac('sha256',key()).update(value).digest('hex')
const code=kind=>`${kind==='topup'?'NAP':'RUT'}${Date.now().toString(36).toUpperCase()}${crypto.randomBytes(3).toString('hex').toUpperCase()}`
const publicAccount=row=>row&&({id:row.id,bankCode:row.bank_code,bankName:row.bank_name,accountName:row.account_name,masked:`•••• ${row.account_last4}`,isDefault:row.is_default})
async function notifyAdmins(client,item){await client.query(`insert into notifications(user_id,kind,title,body,action_url)
  select id,'payment_review',$1,$2,'/admin' from users where role in ('admin','super_admin') and status='active' and deleted_at is null`,[
  item.kind==='topup'?'Có yêu cầu nạp tiền':'Có yêu cầu rút tiền',`${item.code} · ${Number(item.amount_vnd).toLocaleString('vi-VN')}đ`])}
export function paymentConfig(){return {mode:env.paymentMode,manualEnabled:manualEnabled(),bank:manualEnabled()?{code:env.paymentBankCode,name:env.paymentBankName,accountNumber:env.paymentBankAccount,accountName:env.paymentBankAccountName}:null}}
export async function savePayoutAccount(userId,{bankCode,bankName,accountNumber,accountName}){requireManual();const db=database();if(!db)throw error('Cần PostgreSQL để lưu tài khoản.',503);const number=normalizeAccount(accountNumber),name=String(accountName||'').trim().toUpperCase();if(!/^[0-9]{6,20}$/.test(number)||String(bankCode||'').trim().length<2||name.length<2)throw error('Thông tin tài khoản ngân hàng không hợp lệ.');const client=await db.connect();try{await client.query('begin');const pending=await client.query(`select 1 from wallet_cash_requests where user_id=$1 and kind='withdrawal' and status in ('pending','processing') limit 1`,[userId]);if(pending.rowCount)throw error('Không thể đổi tài khoản khi có yêu cầu rút đang chờ.',409,'PENDING_WITHDRAWAL');await client.query('update payout_accounts set is_default=false,updated_at=now() where user_id=$1',[userId]);const row=(await client.query(`insert into payout_accounts(user_id,bank_code,bank_name,account_number_encrypted,account_number_hash,account_last4,account_name,is_default)
 values($1,$2,$3,$4,$5,$6,$7,true) on conflict(user_id,account_number_hash) do update set bank_code=$2,bank_name=$3,account_number_encrypted=$4,account_name=$7,is_default=true,updated_at=now() returning *`,[userId,String(bankCode).trim().toUpperCase(),String(bankName||bankCode).trim(),encrypt(number),hashAccount(number),number.slice(-4),name])).rows[0];await client.query('commit');return publicAccount(row)}catch(e){await client.query('rollback');throw e}finally{client.release()}}
export async function getPaymentOverview(userId){const db=database();if(!db)return {...paymentConfig(),account:null,requests:[]};const [account,requests]=await Promise.all([db.query('select * from payout_accounts where user_id=$1 and is_default=true',[userId]),db.query(`select id,kind,amount_vnd,code,status,bank_reference,review_note,created_at,reviewed_at from wallet_cash_requests where user_id=$1 order by created_at desc limit 30`,[userId])]);return {...paymentConfig(),account:publicAccount(account.rows[0]),requests:requests.rows}}
export async function createTopup(userId,{amountVnd,senderName}){requireManual();if(!env.paymentBankAccount||!env.paymentBankName||!env.paymentBankAccountName)throw error('Quản trị viên chưa cấu hình tài khoản nhận tiền.',503,'PAYMENT_BANK_NOT_CONFIGURED');const db=database(),amount=amountOf(amountVnd),sender=String(senderName||'').trim().toUpperCase();if(sender.length<2)throw error('Phải nhập tên người chuyển tiền.');if(!db)throw error('Cần PostgreSQL.',503);const client=await db.connect();try{await client.query('begin');const pending=await client.query(`select count(*)::int count from wallet_cash_requests where user_id=$1 and kind='topup' and status='pending'`,[userId]);if(pending.rows[0].count>=3)throw error('Bạn đang có quá nhiều yêu cầu nạp chờ duyệt.',429,'TOO_MANY_PENDING_TOPUPS');const item=(await client.query(`insert into wallet_cash_requests(user_id,kind,amount_vnd,code,sender_name) values($1,'topup',$2,$3,$4) returning *`,[userId,amount,code('topup'),sender])).rows[0];await notifyAdmins(client,item);await client.query('commit');return {...item,bank:paymentConfig().bank,transferContent:item.code}}catch(e){await client.query('rollback');throw e}finally{client.release()}}
export async function createWithdrawal(userId,{amountVnd}){requireManual();const db=database(),amount=amountOf(amountVnd);if(!db)throw error('Cần PostgreSQL.',503);const client=await db.connect();try{await client.query('begin');const account=(await client.query('select * from payout_accounts where user_id=$1 and is_default=true for update',[userId])).rows[0];if(!account)throw error('Vui lòng lưu tài khoản nhận trước.');await client.query('insert into wallets(user_id) values($1) on conflict do nothing',[userId]);const wallet=(await client.query('select * from wallets where user_id=$1 for update',[userId])).rows[0];if(Number(wallet.available_vnd)<amount)throw error('Số dư khả dụng không đủ.',402,'INSUFFICIENT_BALANCE');await client.query('update wallets set available_vnd=available_vnd-$2,pending_vnd=pending_vnd+$2,updated_at=now() where user_id=$1',[userId,amount]);const item=(await client.query(`insert into wallet_cash_requests(user_id,kind,amount_vnd,code,payout_account_id) values($1,'withdrawal',$2,$3,$4) returning *`,[userId,amount,code('withdrawal'),account.id])).rows[0];await notifyAdmins(client,item);await client.query('commit');return {...item,payoutAccount:publicAccount(account)}}catch(e){await client.query('rollback');throw e}finally{client.release()}}
export async function listCashRequests(){const db=database();if(!db)return [];const {rows}=await db.query(`select r.*,u.display_name,u.email,p.bank_name,p.account_name,p.account_last4,p.account_number_encrypted from wallet_cash_requests r join users u on u.id=r.user_id left join payout_accounts p on p.id=r.payout_account_id order by (r.status in ('pending','processing')) desc,r.created_at desc limit 200`);return rows.map(row=>({...row,account_number:row.account_number_encrypted?decrypt(row.account_number_encrypted):null,account_number_encrypted:undefined}))}
export async function reviewCashRequest(actor,id,{decision,bankReference,actualAmountVnd,note}){requireManual();if(!['approve','reject'].includes(decision))throw error('Quyết định không hợp lệ.');const reason=String(note||'').trim();if(reason.length<5)throw error('Ghi chú đối soát phải có ít nhất 5 ký tự.');const ref=String(bankReference||'').trim();const db=database(),client=await db.connect();let item;try{await client.query('begin');item=(await client.query('select * from wallet_cash_requests where id=$1 for update',[id])).rows[0];if(!item)throw error('Không tìm thấy yêu cầu.',404);if(item.status!=='pending')throw error('Yêu cầu đã được xử lý.',409,'PAYMENT_ALREADY_REVIEWED');await client.query('insert into wallets(user_id) values($1) on conflict do nothing',[item.user_id]);await client.query('select * from wallets where user_id=$1 for update',[item.user_id]);if(decision==='approve'){
  if(ref.length<4)throw error('Phải nhập mã giao dịch ngân hàng.');if(Number(actualAmountVnd)!==Number(item.amount_vnd))throw error('Số tiền đối soát không khớp yêu cầu.',409,'AMOUNT_MISMATCH');
  let ledger;if(item.kind==='topup'){await client.query('update wallets set available_vnd=available_vnd+$2,updated_at=now() where user_id=$1',[item.user_id,item.amount_vnd]);ledger=(await client.query(`insert into ledger_entries(user_id,direction,amount_vnd,entry_type) values($1,'credit',$2,'manual_topup') returning id`,[item.user_id,item.amount_vnd])).rows[0]}else{await client.query('update wallets set pending_vnd=pending_vnd-$2,updated_at=now() where user_id=$1 and pending_vnd>=$2',[item.user_id,item.amount_vnd]);ledger=(await client.query(`insert into ledger_entries(user_id,direction,amount_vnd,entry_type) values($1,'debit',$2,'manual_withdrawal') returning id`,[item.user_id,item.amount_vnd])).rows[0]}
  item=(await client.query(`update wallet_cash_requests set status=$2,bank_reference=$3,actual_amount_vnd=$4,review_note=$5,reviewed_by=$6,reviewed_at=now(),updated_at=now(),ledger_entry_id=$7 where id=$1 returning *`,[id,item.kind==='topup'?'approved':'paid',ref,actualAmountVnd,reason,actor.id,ledger.id])).rows[0]
 }else{if(item.kind==='withdrawal')await client.query('update wallets set pending_vnd=pending_vnd-$2,available_vnd=available_vnd+$2,updated_at=now() where user_id=$1',[item.user_id,item.amount_vnd]);item=(await client.query(`update wallet_cash_requests set status='rejected',review_note=$2,reviewed_by=$3,reviewed_at=now(),updated_at=now() where id=$1 returning *`,[id,reason,actor.id])).rows[0]}
 await client.query(`insert into admin_audit_logs(actor_id,action,target_type,target_id,reason,metadata) values($1,$2,'wallet_cash_request',$3,$4,$5)`,[actor.id,`cash_${item.kind}_${decision}`,id,reason,{bankReference:ref||null,actualAmountVnd:actualAmountVnd||null,code:item.code}]);await client.query('commit')}catch(e){await client.query('rollback');throw e}finally{client.release()}await notify(item.user_id,{kind:'payment',title:decision==='approve'?(item.kind==='topup'?'Nạp tiền đã được duyệt':'Yêu cầu rút đã chuyển khoản'):'Yêu cầu thanh toán bị từ chối',body:`${item.code} · ${Number(item.amount_vnd).toLocaleString('vi-VN')}đ. ${reason}`,actionUrl:'/vi'});return item}
